"""Add newx geo indexes

Revision ID: 9040bda00263
Revises: a2fe1483762b
Create Date: 2024-11-06 01:46:06.693915

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9040bda00263"
down_revision: Union[str, None] = "a2fe1483762b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "locations", sa.Column("h3_index_9", sa.BigInteger(), nullable=False)
    )
    op.add_column(
        "locations", sa.Column("h3_index_3", sa.BigInteger(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "h3_index_3")
    op.drop_column("locations", "h3_index_9")

    # ### end Alembic commands ###
